
-------------------------git-----------------------------------

CREATE DATABASE DISHA_DCM;
CREATE OR REPLACE SCHEMA INTEGRATION

CREATE OR REPLACE SECRET DISHA_DCM.INTEGRATION.GIT_SECRET
  TYPE = password
  USERNAME = 'Disha-16'
  PASSWORD = ' **************** ';

CREATE OR REPLACE API INTEGRATION dcm_git_cicd_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/kipibi')
  ALLOWED_AUTHENTICATION_SECRETS = (DISHA_DCM.INTEGRATION.GIT_SECRET)
  ENABLED = TRUE;

CREATE OR REPLACE GIT REPOSITORY DISHA_DCM.INTEGRATION.DCM_PROJECT_REPO
  API_INTEGRATION = dcm_git_api_integration
  GIT_CREDENTIALS =  DISHA_DCM.INTEGRATION.GIT_SECRET
  ORIGIN = 'https://github.com/kipibi/CI_CD_STANDARD_TIER_OFFERING_TEMPLATE.git';
