name: "Standard Tier: Automated Snowflake Delivery - Master"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'initialization_template/**'
      - 'dcm_texas_farm_credit_cicd_demo/**'
  push:
    branches:
      - dev
      - main
    paths:
      - 'initialization_template/**'
      - 'dcm_texas_farm_credit_cicd_demo/**'

permissions:
  id-token: write 
  contents: read

jobs:
  dev-environment-plan:
    if: github.event_name == 'pull_request' && github.base_ref == 'dev'
    uses: ./.github/workflows/snowflake-pipeline-dev.yml
    with:
      action_type: 'plan'
    secrets: inherit

  dev-environment-deploy:
    if: github.event_name == 'push' && github.ref_name == 'dev'
    uses: ./.github/workflows/snowflake-pipeline-dev.yml
    with:
      action_type: 'deploy'
    secrets: inherit

  main-environment-plan:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    uses: ./.github/workflows/snowflake-pipeline-main.yml
    with:
      action_type: 'plan'
    secrets: inherit

  main-environment-deploy:
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/snowflake-pipeline-main.yml
    with:
      action_type: 'deploy'
    secrets: inherit
